// File automatically generated by swift-bridge.
#include <stdint.h>
#include <stdbool.h>
typedef struct __swift_bridge__$RipgrepOptionsFFI { bool case_insensitive; bool smart_case; bool fixed_strings; bool word; bool line_regexp; bool multiline; bool dot_matches_new_line; bool invert_match; bool unicode; bool crlf; uint32_t max_count; uint32_t before_context; uint32_t after_context; bool passthru; bool include_hidden; bool follow_links; bool same_file_system; int32_t max_depth; uint64_t max_filesize; bool respect_ignore; bool respect_git_ignore; bool respect_git_global; bool respect_git_exclude; bool respect_parents; bool require_git; bool parallel; bool has_replace; void* replace; void* globs; void* types; } __swift_bridge__$RipgrepOptionsFFI;
typedef struct __swift_bridge__$Option$RipgrepOptionsFFI { bool is_some; __swift_bridge__$RipgrepOptionsFFI val; } __swift_bridge__$Option$RipgrepOptionsFFI;
struct __private__ResultPtrAndPtr __swift_bridge__$ripgrep(void* pattern, void* path, struct __swift_bridge__$RipgrepOptionsFFI options);
struct __private__ResultPtrAndPtr __swift_bridge__$find_files(void* path, struct __swift_bridge__$RipgrepOptionsFFI options);


