name: SwiftyRipgrep

on:
  push:
    branches:
      - main
  pull_request: {}

concurrency:
  group: SwiftyRipgrep-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: swift test --package-path ./fixture
